### ISSUE TITLE
Readme: TimeStamp -> timestamp

### ISSUE THREAD

**Issue by kirill146** [mrexodia/TimeStampFormat#1]
Replace ```log "[{TimeStamp@0}] test"``` with ```log "[{timestamp@0}] test"``` since argument of ```_plugin_registerformatfunction()``` seeems to be case sensitive

**Comment by mrexodia** [comment]
A pull request would be nice 😄

**Comment by kirill146** [comment]
Thanks for the quick reply. PR: https://github.com/mrexodia/TimeStampFormat/pull/2/files
